[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Autonomous Navigation of Mobile Robots"
authors = [{name = "Muhammad Hammad Hussain", email = "muhammadhammadhussain@gmail.com"}]
dynamic = ["version", "description"]
